version: '3'

services: 
    app:
        build:
          context: node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 5s docker-entrypoint.sh
        command: node index.js
        volumes:
          - ./node:/usr/src/app
          - ./node/node_modules:/usr/src/app/node_modules
        tty: true
        depends_on:
          - db
        networks: 
          - app-network
        
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: devfullcycle
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        networks: 
          - app-network

    nginx:
      build:
        context: nginx
      container_name: nginx
      tty: true
      ports:
        - "8080:80"
      depends_on:
        - app
      networks: 
        - app-network


networks: 
  app-network:
    driver: bridge    